name: Release

on: [workflow_dispatch]

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        name: Setup JDK 16
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true

      - name: Semver release
        uses: oknozor/cocogitto-action@v1
        with:
          release: true
          git-user: 'Cog Bot'
          git-user-email: 'mycoolproject@org.org'